In [1]:
# !pip install -q spacy nltk

In [1]:
import nltk

In [2]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /home/renata/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/renata/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /home/renata/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
text_en = """
Trump warned that Iranian forces would be
 "blown off the face of the Earth" if they target US ships.
Meanwhile, Iran's attacks on the UAE threaten to
widen the conflict again.
"""

text_pt = """
O Flamengo oficializou nesta segunda-feira a renovação de
contrato do atacante Bruno Henrique.
O novo vínculo é válido até o fim de 2027
e foi assinado após o treino no Ninho do Urubu.
O vínculo anterior se encerrava em dezembro deste ano.
"""

In [4]:
def inspecionar_texto(texto):
    print("Tipo do objeto", type(texto))
    print("Tamanho em caracteres:", len(texto))
    print("\n Primeiros 100 caracteres:")
    print(texto[0:120])

inspecionar_texto(text_pt)

Tipo do objeto <class 'str'>
Tamanho em caracteres: 241

 Primeiros 100 caracteres:

O Flamengo oficializou nesta segunda-feira a renovação de
contrato do atacante Bruno Henrique.
O novo vínculo é válido

# Tokenização de sentenças

In [5]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tokenize.casual import casual_tokenize

In [6]:
sentencas_pt = sent_tokenize(text_pt, language='portuguese')


for idx, sentenca in enumerate(sentencas_pt):
    print(f"Sentença {idx + 1}: {sentenca.replace("\n", "")}")
    print()

Sentença 1: O Flamengo oficializou nesta segunda-feira a renovação decontrato do atacante Bruno Henrique.

Sentença 2: O novo vínculo é válido até o fim de 2027e foi assinado após o treino no Ninho do Urubu.

Sentença 3: O vínculo anterior se encerrava em dezembro deste ano.

In [7]:
sentencas_en = sent_tokenize(text_en, language='english')

for idx, sentenca in enumerate(sentencas_en):
    print(f"Sentença {idx + 1}: {sentenca.replace("\n", "")}")
    print()

Sentença 1: Trump warned that Iranian forces would be "blown off the face of the Earth" if they target US ships.

Sentença 2: Meanwhile, Iran's attacks on the UAE threaten towiden the conflict again.

In [8]:
words_pt = word_tokenize(text_pt, language="portuguese")

for idx, word in enumerate(words_pt):
    print(f"Word {idx}: {word}")

Word 0: O
Word 1: Flamengo
Word 2: oficializou
Word 3: nesta
Word 4: segunda-feira
Word 5: a
Word 6: renovação
Word 7: de
Word 8: contrato
Word 9: do
Word 10: atacante
Word 11: Bruno
Word 12: Henrique
Word 13: .
Word 14: O
Word 15: novo
Word 16: vínculo
Word 17: é
Word 18: válido
Word 19: até
Word 20: o
Word 21: fim
Word 22: de
Word 23: 2027
Word 24: e
Word 25: foi
Word 26: assinado
Word 27: após
Word 28: o
Word 29: treino
Word 30: no
Word 31: Ninho
Word 32: do
Word 33: Urubu
Word 34: .
Word 35: O
Word 36: vínculo
Word 37: anterior
Word 38: se
Word 39: encerrava
Word 40: em
Word 41: dezembro
Word 42: deste
Word 43: ano
Word 44: .

In [9]:
x_text = "O jogo do @Pedro, jogador do Flamengo foi de #JogadorPraSeleção :-)"
words_pt = word_tokenize(x_text, language="portuguese")

for idx, word in enumerate(words_pt):
    print(f"Token {idx}: {word}")

Token 0: O
Token 1: jogo
Token 2: do
Token 3: @
Token 4: Pedro
Token 5: ,
Token 6: jogador
Token 7: do
Token 8: Flamengo
Token 9: foi
Token 10: de
Token 11: #
Token 12: JogadorPraSeleção
Token 13: :
Token 14: -
Token 15: )

In [10]:
token_pt = casual_tokenize(x_text)

for idx, token in enumerate(token_pt):
    print(f"Token {idx}: {token}")

Token 0: O
Token 1: jogo
Token 2: do
Token 3: @Pedro
Token 4: ,
Token 5: jogador
Token 6: do
Token 7: Flamengo
Token 8: foi
Token 9: de
Token 10: #JogadorPraSeleção
Token 11: :-)

# Normalização: Case folding

In [11]:
tokens = ["Flamengo", "FLAMENGO", "flamengo", "Pedro", "pedro", "Neymar", "neymar"]

tokens_lower = [token.lower() for token in tokens]

print(tokens_lower)

['flamengo', 'flamengo', 'flamengo', 'pedro', 'pedro', 'neymar', 'neymar']

In [12]:
text_pt = "Real Madrid perdeu o último jogo e foi uma real injustiça."

for token in word_tokenize(text_pt, language="portuguese"):
    print(token.lower())

real
madrid
perdeu
o
último
jogo
e
foi
uma
real
injustiça
.

In [13]:
text_pt = """
Programação em python é muito melhor que em javascript.
Quem programa em python sabe o que é programação divirtida.
"""
tokens = list(word_tokenize(text_pt, language="portuguese"))
tokens = [token.lower() for token in tokens]

from collections import Counter

for tuple_tokens in Counter(tokens).most_common(10):
    print(tuple_tokens)

('em', 3)
('programação', 2)
('python', 2)
('é', 2)
('que', 2)
('.', 2)
('muito', 1)
('melhor', 1)
('javascript', 1)
('quem', 1)

In [14]:
text_en = "Jonh went to the bathroom. The john was broken"

for token in word_tokenize(text_en, language="english"):
    print(token.lower())

jonh
went
to
the
bathroom
.
the
john
was
broken

# Tokenize com Spacy

In [15]:
import spacy

# !python -m spacy download en_core_web_md
# !python -m spacy download pt_core_news_md

Collecting en-core-web-md==3.8.0
  Downloading en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 25.4 MB/s  0:00:01m0:00:0100:01
Installing collected packages: en-core-web-md
Successfully installed en-core-web-md-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
Collecting pt-core-news-md==3.8.0
  Downloading pt_core_news_md-3.8.0-py3-none-any.whl (42.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 20.9 MB/s  0:00:02m0:00:0100:01
Installing collected packages: pt-core-news-md
Successfully installed pt-core-news-md-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_md')

In [17]:
nlp_en = spacy.load("en_core_web_md")
nlp_pt = spacy.load("pt_core_news_md")

In [18]:
text_en = """
Trump warned that Iranian forces would be
 "blown off the face of the Earth" if they target US ships.
Meanwhile, Iran's attacks on the UAE threaten to
widen the conflict again.
"""

text_pt = """
O Flamengo oficializou nesta segunda-feira a renovação de
contrato do atacante Bruno Henrique.
O novo vínculo é válido até o fim de 2027
e foi assinado após o treino no Ninho do Urubu.
O vínculo anterior se encerrava em dezembro deste ano.
"""

doc_pt = nlp_pt(text_pt)
doc_en = nlp_en(text_en)


for idx, token in enumerate(doc_pt):
    print(f"Token {idx}: {token}")

Token 0:

Token 1: O
Token 2: Flamengo
Token 3: oficializou
Token 4: nesta
Token 5: segunda-feira
Token 6: a
Token 7: renovação
Token 8: de
Token 9:

Token 10: contrato
Token 11: do
Token 12: atacante
Token 13: Bruno
Token 14: Henrique
Token 15: .
Token 16:

Token 17: O
Token 18: novo
Token 19: vínculo
Token 20: é
Token 21: válido
Token 22: até
Token 23: o
Token 24: fim
Token 25: de
Token 26: 2027
Token 27:

Token 28: e
Token 29: foi
Token 30: assinado
Token 31: após
Token 32: o
Token 33: treino
Token 34: no
Token 35: Ninho
Token 36: do
Token 37: Urubu
Token 38: .
Token 39:

Token 40: O
Token 41: vínculo
Token 42: anterior
Token 43: se
Token 44: encerrava
Token 45: em
Token 46: dezembro
Token 47: deste
Token 48: ano
Token 49: .
Token 50:

In [19]:
def mostrar_tokens_spacy(doc):
    dados = []
    for token in doc:
        dados.append({
            "token": token,
            "é pontuação": token.is_punct,
            "é espaço": token.is_space,
            "é alfa numérico": token.is_alpha,
            "formato": token.shape_
        })
    return dados

import pandas as pd

pd.DataFrame(mostrar_tokens_spacy(doc_pt))

            token  é pontuação  é espaço  é alfa numérico    formato
0              \n        False      True            False         \n
1               O        False     False             True          X
2        Flamengo        False     False             True      Xxxxx
3     oficializou        False     False             True       xxxx
4           nesta        False     False             True       xxxx
5   segunda-feira        False     False            False  xxxx-xxxx
6               a        False     False             True          x
7       renovação        False     False             True       xxxx
8              de        False     False             True         xx
9              \n        False      True            False         \n
10       contrato        False     False             True       xxxx
11             do        False     False             True         xx
12       atacante        False     False             True       xxxx
13          Bruno        False     False             True      Xxxxx
14       Henrique        False     False             True      Xxxxx
15              .         True     False            False          .
16             \n        False      True            False         \n
17              O        False     False             True          X
18           novo        False     False             True       xxxx
19        vínculo        False     False             True       xxxx
20              é        False     False             True          x
21         válido        False     False             True       xxxx
22            até        False     False             True        xxx
23              o        False     False             True          x
24            fim        False     False             True        xxx
25             de        False     False             True         xx
26           2027        False     False            False       dddd
27             \n        False      True            False         \n
28              e        False     False             True          x
29            foi        False     False             True        xxx
30       assinado        False     False             True       xxxx
31           após        False     False             True       xxxx
32              o        False     False             True          x
33         treino        False     False             True       xxxx
34             no        False     False             True         xx
35          Ninho        False     False             True      Xxxxx
36             do        False     False             True         xx
37          Urubu        False     False             True      Xxxxx
38              .         True     False            False          .
39             \n        False      True            False         \n
40              O        False     False             True          X
41        vínculo        False     False             True       xxxx
42       anterior        False     False             True       xxxx
43             se        False     False             True         xx
44      encerrava        False     False             True       xxxx
45             em        False     False             True         xx
46       dezembro        False     False             True       xxxx
47          deste        False     False             True       xxxx
48            ano        False     False             True        xxx
49              .         True     False            False          .
50             \n        False      True            False         \n

# Limpar o texto

In [ ]:
from nltk.corpus import stopwords

In [20]:
from nltk.corpus import stopwords

def limpar_texto(text, language="english", custom_stopwords=[]):

    stopwords_ = set(stopwords.words(language) + custom_stopwords)
    tokens = [token.text.lower() for token in nlp_pt(text)]
    tokens = [
        token
        for token in tokens
        if token not in stopwords_ and token.isalpha()
    ]
    return tokens

limpar_texto(text_pt, language="portuguese")

['flamengo',
 'oficializou',
 'nesta',
 'renovação',
 'contrato',
 'atacante',
 'bruno',
 'henrique',
 'novo',
 'vínculo',
 'válido',
 'fim',
 'assinado',
 'após',
 'treino',
 'ninho',
 'urubu',
 'vínculo',
 'anterior',
 'encerrava',
 'dezembro',
 'deste',
 'ano']

In [21]:
text_pt = """
Programação em python é muito melhor que em javascript.
Quem programa em python sabe o que é programação divertida.
"""
tokens = limpar_texto(text_pt, language="portuguese", custom_stopwords=["sabe"])

for tuple_tokens in Counter(tokens).most_common(10):
    print(tuple_tokens)

('programação', 2)
('python', 2)
('melhor', 1)
('javascript', 1)
('programa', 1)
('divertida', 1)

In [22]:
tokens = limpar_texto(text_en, language="english")

for tuple_tokens in Counter(tokens).most_common(10):
    print(tuple_tokens)

('trump', 1)
('warned', 1)
('iranian', 1)
('forces', 1)
('would', 1)
('blown', 1)
('face', 1)
('earth', 1)
('target', 1)
('us', 1)

In [23]:
stopwords.words("portuguese")

['a',
 'à',
 'ao',
 'aos',
 'aquela',
 'aquelas',
 'aquele',
 'aqueles',
 'aquilo',
 'as',
 'às',
 'até',
 'com',
 'como',
 'da',
 'das',
 'de',
 'dela',
 'delas',
 'dele',
 'deles',
 'depois',
 'do',
 'dos',
 'e',
 'é',
 'ela',
 'elas',
 'ele',
 'eles',
 'em',
 'entre',
 'era',
 'eram',
 'éramos',
 'essa',
 'essas',
 'esse',
 'esses',
 'esta',
 'está',
 'estamos',
 'estão',
 'estar',
 'estas',
 'estava',
 'estavam',
 'estávamos',
 'este',
 'esteja',
 'estejam',
 'estejamos',
 'estes',
 'esteve',
 'estive',
 'estivemos',
 'estiver',
 'estivera',
 'estiveram',
 'estivéramos',
 'estiverem',
 'estivermos',
 'estivesse',
 'estivessem',
 'estivéssemos',
 'estou',
 'eu',
 'foi',
 'fomos',
 'for',
 'fora',
 'foram',
 'fôramos',
 'forem',
 'formos',
 'fosse',
 'fossem',
 'fôssemos',
 'fui',
 'há',
 'haja',
 'hajam',
 'hajamos',
 'hão',
 'havemos',
 'haver',
 'hei',
 'houve',
 'houvemos',
 'houver',
 'houvera',
 'houverá',
 'houveram',
 'houvéramos',
 'houverão',
 'houverei',
 'houverem',
 'houveremos',
 'houveria',
 'houveriam',
 'houveríamos',
 'houvermos',
 'houvesse',
 'houvessem',
 'houvéssemos',
 'isso',
 'isto',
 'já',
 'lhe',
 'lhes',
 'mais',
 'mas',
 'me',
 'mesmo',
 'meu',
 'meus',
 'minha',
 'minhas',
 'muito',
 'na',
 'não',
 'nas',
 'nem',
 'no',
 'nos',
 'nós',
 'nossa',
 'nossas',
 'nosso',
 'nossos',
 'num',
 'numa',
 'o',
 'os',
 'ou',
 'para',
 'pela',
 'pelas',
 'pelo',
 'pelos',
 'por',
 'qual',
 'quando',
 'que',
 'quem',
 'são',
 'se',
 'seja',
 'sejam',
 'sejamos',
 'sem',
 'ser',
 'será',
 'serão',
 'serei',
 'seremos',
 'seria',
 'seriam',
 'seríamos',
 'seu',
 'seus',
 'só',
 'somos',
 'sou',
 'sua',
 'suas',
 'também',
 'te',
 'tem',
 'tém',
 'temos',
 'tenha',
 'tenham',
 'tenhamos',
 'tenho',
 'terá',
 'terão',
 'terei',
 'teremos',
 'teria',
 'teriam',
 'teríamos',
 'teu',
 'teus',
 'teve',
 'tinha',
 'tinham',
 'tínhamos',
 'tive',
 'tivemos',
 'tiver',
 'tivera',
 'tiveram',
 'tivéramos',
 'tiverem',
 'tivermos',
 'tivesse',
 'tivessem',
 'tivéssemos',
 'tu',
 'tua',
 'tuas',
 'um',
 'uma',
 'você',
 'vocês',
 'vos']

# Stemming com Porter e Snowball

Reduz as palavras flexonadas para radical

In [24]:
from nltk.stem import PorterStemmer, SnowballStemmer

stemmer_porter = PorterStemmer()
stemmer_snowball = SnowballStemmer(language="portuguese")

In [25]:
porter = PorterStemmer()

palavras_en = ["running", "runs", "runner", "studies", "studying", "houses", "better"]

for palavra in palavras_en:
    print(palavra, "->", porter.stem(palavra))

running -> run
runs -> run
runner -> runner
studies -> studi
studying -> studi
houses -> hous
better -> better

In [26]:
snowball_pt = SnowballStemmer("portuguese")

palavras_pt = [
    "correr",
    "correndo",
    "correu",
    "corrida",
    "casas",
    "casinha",
    "felizmente",
    "programação",
    "programador",
    "programando"
]

for palavra in palavras_pt:
    print(palavra, "->", snowball_pt.stem(palavra))

correr -> corr
correndo -> corr
correu -> corr
corrida -> corr
casas -> cas
casinha -> casinh
felizmente -> feliz
programação -> program
programador -> program
programando -> program

In [27]:
text_pt = """
Programação em python é muito melhor que em javascript.
Quem programa em python sabe o que é programação divertida.
"""
tokens = limpar_texto(text_pt, language="portuguese", custom_stopwords=["sabe"])
tokens_stem = [stemmer_snowball.stem(token) for token in tokens]
for tuple_tokens in Counter(tokens_stem).most_common(10):
    print(tuple_tokens)

('program', 3)
('python', 2)
('melhor', 1)
('javascript', 1)
('divert', 1)

# Lematização

Palavras flexonadas -> lema (representação no dicionário)

In [28]:
text_pt = """
Programação em python é muito melhor que em javascript.
Quem programa em python sabe o que é programação divertida.
"""

doc = nlp_pt(text_pt)

stopwords_ = set(stopwords.words("portuguese") )

tokens = [
    token.lemma_.lower()
    for token in doc
]

tokens = [
    token
    for token in tokens
    if token not in stopwords_ and token.isalpha()
]

for tuple_tokens in Counter(tokens).most_common(10):
    print(tuple_tokens)

('programação', 2)
('python', 2)
('bom', 1)
('javascript', 1)
('programa', 1)
('saber', 1)
('divertido', 1)

In [29]:
frase = "Os jogadores estavam correndo e comemorando a vitória no estádio."

doc = nlp_pt(frase)

comparacao = []

for token in doc:
    if token.is_alpha:
        palavra = token.text.lower()
        stem = snowball_pt.stem(palavra)
        lema = token.lemma_

        comparacao.append({
            "palavra": palavra,
            "stemming": stem,
            "lematização": lema,
            "classe_gramatical": token.pos_
        })

pd.DataFrame(comparacao)

       palavra stemming lematização classe_gramatical
0           os       os           o               DET
1    jogadores  jogador     jogador              NOUN
2      estavam    estav       estar               AUX
3     correndo     corr      correr              VERB
4            e        e           e             CCONJ
5  comemorando  comemor   comemorar              VERB
6            a        a           o               DET
7      vitória    vitór     vitória              NOUN
8           no       no        em o               ADP
9      estádio   estádi     estádio              NOUN